[template]
src = "workday.py.tmpl"
dest = "/opt/ltv/workday/fetch_config.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
